# Generated by Django 5.2 on 2025-01-01 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the job was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the job was last updated')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', help_text='Overall status of the job', max_length=20)),
                ('total_items', models.PositiveIntegerField(default=0, help_text='Total number of items to process')),
                ('processed_items', models.PositiveIntegerField(default=0, help_text='Number of items processed so far')),
                ('error_message', models.TextField(blank=True, help_text='Details about any job-level error', null=True)),
                ('config', models.JSONField(blank=True, help_text='Optional configuration parameters for the job', null=True)),
            ],
            options={
                'verbose_name': 'Ingestion Job',
                'verbose_name_plural': 'Ingestion Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IngestionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_value', models.TextField(help_text='Raw input value from CSV (topic string or URL)')),
                ('source_type', models.CharField(choices=[('TOPIC', 'Topic'), ('LINK', 'Link')], help_text='Whether the input is a TOPIC or a LINK', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', help_text='Processing status of this item', max_length=20)),
                ('result_page_title', models.CharField(blank=True, help_text='Resolved Wikipedia page title after processing', max_length=512, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Details about any item-level error', null=True)),
                ('meta', models.JSONField(blank=True, help_text='Arbitrary metadata captured during processing', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the item was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the item was last updated')),
                ('job', models.ForeignKey(help_text='Parent ingestion job', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.ingestionjob')),
            ],
            options={
                'verbose_name': 'Ingestion Item',
                'verbose_name_plural': 'Ingestion Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ingestionitem',
            index=models.Index(fields=['status'], name='api_ingesti_status_7c1cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionitem',
            index=models.Index(fields=['source_type'], name='api_ingesti_source__a2fff8_idx'),
        ),
    ]
