"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

This settings module loads configuration from environment variables,
configures logging, and keeps SQLite for Django metadata.
"""

from pathlib import Path
import os
import environ  # django-environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment
env = environ.Env(
    DJANGO_DEBUG=(bool, False),
    REQUEST_TIMEOUT=(int, 60),
    MAX_WORKERS=(int, 4),
    RAG_CHUNK_SIZE=(int, 1000),
    RAG_CHUNK_OVERLAP=(int, 150),
)
# Read .env file if present
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Security/Runtime
SECRET_KEY = env("DJANGO_SECRET_KEY", default="unsafe-dev-key-change-me")
DEBUG = env("DEBUG", default=False)
# Allow list; default covers common dev hosts
ALLOWED_HOSTS = env.list(
    "ALLOWED_HOSTS",
    default=[".kavia.ai", "localhost", "127.0.0.1", "testserver"],
)

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_yasg",
    "corsheaders",
    "api",
    # Optional developer utilities (enabled if installed)
    "django_extensions",
]

MIDDLEWARE = [
    # CORS early to handle OPTIONS
    "corsheaders.middleware.CorsMiddleware",
    # Security and common stack
    "django.middleware.common.CommonMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Attach request IDs for structured logging
    "api.middleware.RequestIDMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database (Keep SQLite for Django metadata as requested)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = "static/"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS and proxy headers (preserve existing behavior)
CORS_ALLOW_ALL_ORIGINS = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
X_FRAME_OPTIONS = "ALLOWALL"

# DRF config including centralized exception handler
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        # Browsable API can be added in DEBUG if desired
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ],
    "EXCEPTION_HANDLER": "api.exception_handlers.custom_exception_handler",
}

# RAG / Neo4j / LLM configuration defaults (read by future modules)
NEO4J_URI = env("NEO4J_URI", default="")
NEO4J_USER = env("NEO4J_USER", default="")
NEO4J_PASSWORD = env("NEO4J_PASSWORD", default="")

LLM_PROVIDER = env("LLM_PROVIDER", default="")
EMBEDDINGS_PROVIDER = env("EMBEDDINGS_PROVIDER", default="")
OPENAI_API_KEY = env("OPENAI_API_KEY", default="")  # Optional

RAG_CHUNK_SIZE = env.int("RAG_CHUNK_SIZE", default=1000)
RAG_CHUNK_OVERLAP = env.int("RAG_CHUNK_OVERLAP", default=150)
REQUEST_TIMEOUT = env.int("REQUEST_TIMEOUT", default=60)
MAX_WORKERS = env.int("MAX_WORKERS", default=4)

# Logging configuration for console output at INFO level
LOG_LEVEL = "DEBUG" if DEBUG else "INFO"
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            # Include optional structured context dict if present (injected via build_log_ctx)
            "format": "%(asctime)s | %(levelname)s | %(name)s | %(message)s | %(context)s",
        },
        "simple": {
            "format": "%(levelname)s: %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "level": LOG_LEVEL,
            "stream": "ext://sys.stdout",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "api": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}
